#!/bin/bash
export SHELL=/data/data/com.termux/files/usr/bin/bash
ssh home
#ssh home -t "export PS1_ovrrde='\\[\\e[1;32m\\]SSH \\[\\e[0m\\]\\[\\e[1;33m\\]\w\n \\[\\e[0m\\]\\[\\e[1;31m\\]𝝅 \\[\\e[0m\\]\\[\\e[0;32m\\] ' ; exec bash"
